### ISSUE TITLE
'.meta' in project name is resulting in wrong path resolution

### ISSUE THREAD

**Issue by maxwassiljew** [mateodelnorte/meta-project#7]
If your meta folder is named smth. like 'abc.meta' adding a new project will cause this error:

```
adding abc.pro1 to .gitignore at /home/user/dev/src/abc.gitignore/.meta
/home/user/dev/src/abc.gitignore/.meta does not exists. Creating it now.
fs.js:122
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/user/dev/src/abc.gitignore/.meta'
    at Object.openSync (fs.js:448:3)
    at module.exports (/home/user/.npm/lib/node_modules/meta/node_modules/meta-project/lib/addToGitIgnore.js:12:23)
    at find (/home/user/.npm/lib/node_modules/meta/node_modules/meta-project/bin/meta-project-add:66:9)
    at findIn (/home/user/.npm/lib/node_modules/meta/node_modules/find-file-recursively-up/index.js:18:14)
    at module.exports (/home/user/.npm/lib/node_modules/meta/node_modules/find-file-recursively-up/index.js:28:10)
    at exec (/home/user/.npm/lib/node_modules/meta/node_modules/meta-project/bin/meta-project-add:60:7)
    at module.exports (/home/user/.npm/lib/node_modules/meta/node_modules/meta-exec/index.js:56:18)
    at exec (/home/user/.npm/lib/node_modules/meta/node_modules/meta-project/bin/meta-project-add:51:5)
    at module.exports (/home/user/.npm/lib/node_modules/meta/node_modules/meta-exec/index.js:56:18)
    at mkdirp (/home/user/.npm/lib/node_modules/meta/node_modules/meta-project/bin/meta-project-add:44:3)
```
/home/user/dev/src/**abc.meta**/.meta -> /home/user/dev/src/**abc.gitignore**/.meta does not exists

Maybe thats the place to check:
`addToGitIgnore(metafilePath.replace('.meta', '.gitignore'), destFolder);
`

**Comment by aleclarson** [comment]
This was fixed by 3dfcfd3fae4b4b8f26d6aa50b9160d15fe231d3a.

@mateodelnorte Did you ever release that?

**Comment by mateodelnorte** [comment]
Nope. Made a mental note to get semantic-release on this project. That'd be preferred. I can look into that now.

**Comment by aleclarson** [comment]
@mateodelnorte Sweet. I think you can cherry-pick this: https://github.com/mateodelnorte/get-meta-file/pull/6/commits/92e2a0844b1e12b5d2ad9febbd76e3efa75d81bd

**Comment by aleclarson** [comment]
Here's a git patch:

```sh 
curl https://gist.githubusercontent.com/aleclarson/a05ddf34bcc9395a9e53f88b921fc347/raw/917a5a64f7e0fd0966982af6bc935deb5673853f/ci-semantic-release.patch | git apply -v
```

**Comment by mateodelnorte** [comment]
Went ahead and manually bumped version and published, to get things moving: 
```
+ meta-project@0.0.5
```
@maxwassiljew Can you confirm if this is fixed in 0.0.5? Thx

**Comment by aleclarson** [comment]
I can confirm for him/her. :)

PS: Are you aware of this? https://nodesource.com/blog/semver-tilde-and-caret/

**Comment by maxwassiljew** [comment]
thx @aleclarson :), also confirmation from my side
